# Generated by Django 2.2.1 on 2019-05-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0002_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
