# Generated by Django 2.2.1 on 2019-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0003_remove_message_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=1),
        ),
    ]
