# Generated by Django 2.2.1 on 2019-05-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0006_auto_20190527_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='users_profile_images'),
            preserve_default=False,
        ),
    ]
