# Generated by Django 2.2.1 on 2019-05-29 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0010_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='message',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replied_message', to='messages_api.Message'),
        ),
    ]
