# Generated by Django 2.2.1 on 2019-05-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0011_auto_20190529_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay',
            name='replay_content',
            field=models.TextField(),
        ),
    ]
