# Generated by Django 2.2.1 on 2019-05-30 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0016_message_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
